<?php
session_start();
if(!isset($_SESSION['username']))
{
header('location:index.php');
}
$id=$_GET['id'];
$pcode=$_POST['pcode'];
$pname=$_POST['pname'];
$price=$_POST['price'];
$quantity=$_POST['quantity'];
$categories=$_POST['categories'];
$sub_cat=@$_POST['sub_cat'];
$image=$_POST['image1'];
if($image=='')
{
$fname=@$_FILES['image']['name'];
$tname=@$_FILES['image']['tmp_name'];
$s=move_uploaded_file($tname,"image/".$fname);
//if($s==true)
//{
include_once('../connect.php');
$res=mysql_query("update product set pcode='$pcode',pname='$pname',price='$price',pquantity='$quantity',category='$categories',pimage='$fname' where pid=$id") or die(mysql_error());
$c=mysql_affected_rows($con);
if($c>0)
{
header('location:manageproduct.php');
}
else
{
header('location:manageproduct.php');
}
}
else
{
include_once("../connect.php");
$res=mysql_query("update product set pcode='$pcode',pname='$pname',price='$price',pquantity='$quantity',category='$categories',pimage='$image' where pid=$id") or die(mysql_error());
$c=mysql_affected_rows($con);
if($c>0)
{
header('location:manageproduct.php');
}
else
{
header('location:manageproduct.php');
}
}
//}
?>
